### ISSUE TITLE
Input, select, iframe and others fields disappear

### ISSUE THREAD

**Issue by antoniomaxs** [nedaszilinskas/Odoo-CMS-Embed-HTML-Building-Block#1]
Hello,

When in embed module you add fields like input, select or iframe this fields are not stored, you can view the fields in preview mode but when you save changes this fields disappear.

Thank you for your help.

**Comment by nedaszilinskas** [comment]
Hello antoniomaxs,

Do you get any browser console error?

Here is a demo on how I added a custom bootstrap 3 form with various inputs and styles from http://bootsnipp.com/snippets/featured/bootstrap-form-theme and all works fine.

Video: http://recordit.co/creicpwIWY

Please try it on clean DB and make sure its Odoo 8, not 9.

If the issue still exists please reopen with more details.
